# Generated by Django 5.0.3 on 2024-04-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creater_at',
            new_name='created_at',
        ),
    ]
