# Generated by Django 5.0.3 on 2024-06-24 07:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.upload_filepath),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to=blog.models.upload_filepath),
        ),
    ]
